Update schema.json with "validationSchema"
smart-data-models/dataModel.Weather pull request #22
Opened 2024-05-06 07:20 UTC by feki-rihab

2024-05-06 15:35 UTC, flopezag commented
Missing to include the corresponding example in the example.jsonld with the new property

2024-05-06 15:35 UTC, flopezag requested changes

2024-05-06 15:35 UTC, flopezag commented on WeatherAlert/schema.json
> +  "validationSchema": "https://github.com/smart-data-models/dataModel.Weather/edit/master/WeatherAlert/schema.json",
No, validationSchema is not a key property of the schema.json but a new property that should be defined inside "properties": { }, with the corresponding type and description, where type should be a string, and description should make reference to the corresponding URL in the Model and description about the URL to the corresponding validation schema of the data model and you can put a default value of the link to the validationSchema.

2024-05-08 12:52 UTC, albertoabellagarcia commented
This attribute is not necessary because it is the$id of the schema. Indeed it can be retrieved with this function of the pysmartdatamodels package

import json
from pysmartdatamodels import pysmartdatamodels as sdm

dataModel, subject = "AgriSoil", "dataModel.Agrifood"

result = sdm.list_datamodel_metadata(dataModel, subject)
print(result["jsonSchemaUrl"])
with open("payload2.json", "w") as file:
    json.dump(result, file, indent=2)

2024-05-08 12:52 UTC, closed without merging

2024-05-13 09:05 UTC, feki-rihab commented
Would it make sense to add the validationSchema in these examples instead of the $id or what is the compromise. 
I did this PR to update the schema.json of the data models to be aligned with the waterverse fair principles requirements. 

Let me know how we can solve this, alo @flopezag could you suggest what best to do in this situation?

2024-05-13 09:16 UTC, albertoabellagarcia commented
I don't see the reason for this because you already have not only the link you need, but also the function for retrieving it. Could you be more precise about what FAIR principle is enforced with your contribution and not with the actual solution?

2024-05-13 09:41 UTC, feki-rihab commented
Fernando can elaborate better on these fair principles I believe. He will take a look into this once he is available :) the update of the schema was upon his request.